# Generated by Django 5.0.6 on 2024-07-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history", name="price", field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="SearchParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=100)),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField()),
                ("infants", models.IntegerField()),
            ],
            options={
                "unique_together": {("destination", "adults", "children", "infants")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="search_params",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.searchparams",
            ),
            preserve_default=False,
        ),
    ]
