# Generated by Django 5.0.6 on 2024-07-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_history_price_searchparams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="search_params",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.searchparams",
            ),
        ),
    ]
